version: '3'
services:
  db:
    image: postgres
    ports:
      - "8001:5432"
    environment:
      POSTGRES_USER: catchpy
      POSTGRES_PASSWORD: catchpy
      POSTGRES_DB: catchpy
  web:
    build: 
      context: .
      args:
        REQUIREMENTS_FILE: catchpy/requirements/dev.txt
    image: hx/catchpy:dev
    command: ["./wait-for-it.sh", "db:5432", "--", "./docker_entrypoint.sh"]
    volumes:
      - .:/code
    ports:
      - "9000:8000"
    depends_on:
      - db
    environment:
      CATCHPY_DOTENV_PATH: "/code/docker_dotenv.env"
    networks:
      default:
      public:
        aliases:
          - catchpy.localhost

networks:
  public:

