# Generated by Django 2.2.4 on 2020-06-03 18:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('anno', '0006_auto_20190701_1508'),
    ]

    operations = [
        migrations.AddField(
            model_name='anno',
            name='public',
            field=models.BooleanField(db_index=True, default=True),
        ),
    ]
