# Generated by Django 2.2.4 on 2020-06-03 18:45

from django.db import migrations

def populate_public(apps, schema_editor):
    AnnoModel = apps.get_model('anno', 'Anno')
    for row in AnnoModel.objects.all():
        if len(row.can_read) > 0:
            row.public = False
            row.save(update_fields=['public'])


class Migration(migrations.Migration):
    dependencies = [
        ('anno', '0007_anno_public'),
    ]

    operations = [
        migrations.RunPython(
            populate_public,
            reverse_code=migrations.RunPython.noop,
        ),
    ]

